const state={summary:null,selected:null};
const $=q=>document.querySelector(q);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const short=(v,n=115)=>{v=String(v??"").replace(/\s+/g," ");return v.length>n?`${v.slice(0,n)}…`:v};
const duration=seconds=>{if(seconds==null||!Number.isFinite(seconds))return "等待首个完成包以估算";seconds=Math.round(seconds);const h=Math.floor(seconds/3600),m=Math.floor(seconds%3600/60),s=seconds%60;return h?`${h}小时${m}分`:(m?`${m}分${s}秒`:`${s}秒`)};
async function api(path,options){const r=await fetch(path,{cache:"no-store",...options});if(!r.ok)throw new Error(await r.text()||r.status);return r.json()}
function metrics(summary){const c=summary.counts||{},p=summary.progress||{},total=summary.package_count||0,done=p.completed??((c.success||0)+(c.no_rule||0)+(c.failed||0)),active=p.active??0,queued=p.queued??Math.max(0,total-done-active),percent=total?Math.round(done*1000/total)/10:0;const values=[[total,"上下文包"],[queued,"排队中"],[active,"实际处理中"],[c.success||0,"成功"],[c.no_rule||0,"无规则"],[c.failed||0,"失败"]];$("#metrics").innerHTML=values.map(([v,l])=>`<div class="metric"><b>${v}</b><span>${l}</span></div>`).join("");$("#progress").innerHTML=`<div class="progress-head"><b>完成 ${percent}% · ${done} / ${total}</b><span>处理中 ${active} · 队列 ${queued} · ${p.throughput_per_minute?p.throughput_per_minute.toFixed(1)+" 包/分钟":"正在测量吞吐"}</span></div><div class="progress-track" role="progressbar" aria-valuemin="0" aria-valuemax="${total}" aria-valuenow="${done}" aria-label="规则抽取完成进度"><div class="progress-fill" style="width:${percent}%"></div></div><div class="meta">已运行 ${duration(p.elapsed_seconds)} · 预计剩余 ${duration(p.estimated_remaining_seconds)}。估算按已完成上下文包的实际平均吞吐计算，会随并发与模型负载更新。</div>`}
function filtered(){const q=$("#query").value.toLowerCase(),f=$("#filter").value;return state.summary.packages.filter(p=>(!f||p.status===f)&&(!q||JSON.stringify(p).toLowerCase().includes(q)))}
function renderList(){const rows=filtered();$("#list").innerHTML=rows.length?rows.map(p=>`<button class="row ${p.id===state.selected?"selected":""}" data-id="${p.id}"><b>${p.id} <span class="badge ${p.status}">${p.status}</span>${p.feedback?`<span class="badge ${p.feedback.verdict}">${p.feedback.verdict}</span>`:""}</b><small>${esc(short(p.snippet))}</small><small>${esc((p.section_path||[]).join(" / "))}</small></button>`).join(""):'<div class="empty">没有符合筛选条件的包。</div>';document.querySelectorAll("[data-id]").forEach(x=>x.onclick=()=>select(x.dataset.id))}
function unitCard(unit){return `<div class="content"><b>${esc(unit.id)} <span class="badge">${esc(unit.type)}</span></b><span class="meta">第 ${Number(unit.source?.page??-1)+1} 页 · ${esc(unit.source?.original_block_id||"")}</span><br>${esc(typeof unit.content==='string'?unit.content:JSON.stringify(unit.content))}</div>`}
function assetCard(asset,packageId){const u=asset.unit;let body=u.type==='table'&&typeof u.content==='string'&&u.content.includes('<table')?u.content:`<pre>${esc(typeof u.content==='string'?u.content:JSON.stringify(u.content))}</pre>`;if(asset.resolved_path)body=`<img src="/asset/${encodeURIComponent(packageId)}/${encodeURIComponent(u.id)}" alt="${esc(asset.caption||u.id)}">${body}`;return `<div class="asset"><b>${esc(u.id)} <span class="badge">${esc(u.type)}</span></b><p class="meta">${esc(asset.caption||"")}</p>${body}</div>`}
function rules(ruleset){if(!ruleset)return '<div class="empty">尚无成功解析的结构化规则。</div>';return `<pre>${esc(JSON.stringify(ruleset.rules,null,2))}</pre>`}
function parseStatus(detail){const s=detail.state||{};if(s.status==='success')return `<span class="badge success">解析通过并已写入图</span> ${esc((s.rule_ids||[]).length)} 条规则`;if(s.status==='no_rule')return '<span class="badge no_rule">模型明确无规则</span>';if(s.status==='failed')return `<span class="badge failed">解析/处理失败</span><div class="error">${esc(s.failure_code||"")} ${esc(s.failure_reason||"")}</div>`;return `<span class="badge ${esc(s.status||'pending')}">${esc(s.status||'pending')}</span>`}
function feedback(detail){const f=detail.feedback;return `<div class="feedback"><h3>人工反馈</h3>${f?`<p>当前保存：<span class="badge ${f.verdict}">${f.verdict}</span> <span class="meta">${esc(f.saved_at)}</span></p>`:""}<label><input type="radio" name="verdict" value="appropriate" ${f?.verdict==='appropriate'?'checked':''}> 抽取结果合适</label> <label><input type="radio" name="verdict" value="inappropriate" ${f?.verdict==='inappropriate'?'checked':''}> 不合适</label><label>标准结果（不合适时必填）<textarea id="standard">${esc(f?.standard_result||"")}</textarea></label><label>说明<textarea id="note">${esc(f?.note||"")}</textarea></label><button id="save-feedback">保存反馈</button><span id="feedback-status" class="meta"></span></div>`}
async function select(id){state.selected=id;renderList();$("#detail").innerHTML='<div class="empty">读取包资源与抽取记录…</div>';try{const d=await api(`/api/package/${encodeURIComponent(id)}`);const r=d.resolved;$("#detail").innerHTML=`<h2>${esc(id)}</h2><p class="meta">${esc((r.section_path||[]).join(" / "))}</p><div class="group"><h3>处理与解析状态</h3>${parseStatus(d)}</div><div class="group"><h3>核心正文</h3>${r.core_units.map(unitCard).join("")}</div><div class="group"><h3>支撑内容</h3>${r.support_units.map(unitCard).join("")||'<span class="meta">无</span>'}</div><div class="group"><h3>确定条件</h3>${r.constraints.map(x=>`<span class="badge">${esc(x.type)}：${esc(x.value)}</span>`).join("")||'<span class="meta">无</span>'}</div><div class="group"><h3>所有关联资源（图、表、公式）</h3><div class="assets">${r.assets.map(a=>assetCard(a,id)).join("")||'<span class="meta">无</span>'}</div></div><div class="two"><div class="group"><h3>第一次模型抽取（DSL 初稿）</h3><pre>${esc(d.model_outputs.generate||'尚未产生')}</pre></div><div class="group"><h3>反思稀疏补丁（仅输出修改、删除与新增）</h3><pre>${esc(d.model_outputs.reflect||'尚未产生')}</pre></div></div><div class="group"><h3>本地应用补丁后的最终 DSL</h3><pre>${esc(d.model_outputs.candidate||'尚未产生')}</pre></div><div class="group"><h3>结构化解析结果</h3>${rules(d.ruleset)}</div>${feedback(d)}`;$("#save-feedback").onclick=()=>saveFeedback(id)}catch(e){$("#detail").innerHTML=`<div class="error">读取失败：${esc(e.message)}</div>`}}
async function saveFeedback(id){const verdict=document.querySelector('input[name="verdict"]:checked')?.value;if(!verdict){$("#feedback-status").textContent='请选择判断。';return}try{await api('/api/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({context_package_id:id,verdict,standard_result:$("#standard").value,note:$("#note").value})});$("#feedback-status").textContent='已保存。'}catch(e){$("#feedback-status").textContent=`保存失败：${e.message}`}}
async function refreshSummary(){try{state.summary=await api('/api/summary');metrics(state.summary);renderList();$("#status").textContent=`Run: ${state.summary.run_id||'尚未开始'} · ${new Date().toLocaleTimeString()}`}catch(e){$("#status").textContent=`读取失败：${e.message}`}}
$("#query").oninput=renderList;$("#filter").onchange=renderList;$("#refresh-detail").onclick=()=>state.selected&&select(state.selected);setInterval(()=>{if($("#live").checked)refreshSummary()},4000);refreshSummary();
